# Generated by Django 3.2.5 on 2021-10-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('app_url', models.URLField(verbose_name='link_app')),
                ('github_url', models.URLField(verbose_name='link_github')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='webapp')),
            ],
        ),
    ]
