# Generated by Django 3.2.5 on 2021-10-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='webapp')),
                ('about_me', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Vanesa',
        ),
    ]
